# Generated by Django 3.1.2 on 2020-10-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='chave',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Rede Social'),
        ),
    ]
